# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: always
    env_file:
      - .env
    networks:
      - ridenitt-network
  
networks:
  ridenitt-network:
    external: true